CREATE DATABASE BIBLIOTEKA
USE BIBLIOTEKA
GO

CREATE TABLE KNJIGA(
KNJIGAID INT IDENTITY(1, 1) PRIMARY KEY NOT NULL,
UDK CHAR(30),
ISBN CHAR(30),
NAZIV CHAR(30)
)

CREATE TABLE CITALAC(
CITALACID INT IDENTITY(1, 1) PRIMARY KEY,
MATICNIBROJ INT,
IME CHAR(20),
PREZIME CHAR(25),
MESTO CHAR(30),
ADRESA CHAR(30),
TELEFON CHAR(30)
)

CREATE TABLE AUTOR(
AUTORID INT IDENTITY(1, 1) PRIMARY KEY,
IME CHAR(20),
PREZIME CHAR(25),
DATUMRODJENJA DATE,
ADRESA CHAR(30),
ZVANJE CHAR(30)
)

CREATE TABLE IZDAVAC(
IZDAVACID INT IDENTITY(1, 1) PRIMARY KEY,
NAZIVIZDAVACA CHAR(20),
ADRESA CHAR(30)
)

CREATE TABLE IZDALI(
IZDAVACID INT,
KNJIGAID INT,
GODINA INT,
CONSTRAINT IZDAVACCCC FOREIGN KEY(IZDAVACID) REFERENCES IZDAVAC(IZDAVACID),
CONSTRAINT KNJ FOREIGN KEY(KNJIGAID) REFERENCES KNJIGA(KNJIGAID),
)

CREATE TABLE NA_CITANJU(
KNJIGAID INT,
CITALACID INT,
DATUMUZIMANJA DATE,
DATUMVRACANJA DATE,
CONSTRAINT KNJIGAA FOREIGN KEY(KNJIGAID) REFERENCES KNJIGA(KNJIGAID),
CONSTRAINT CITALACC FOREIGN KEY(CITALACID) REFERENCES CITALAC(CITALACID)
)

CREATE TABLE NAPISALI(
AUTORID INT,
KNJIGAID INT
CONSTRAINT AUTORR FOREIGN KEY(AUTORID) REFERENCES AUTOR(AUTORID),
CONSTRAINT KN FOREIGN KEY(KNJIGAID) REFERENCES KNJIGA(KNJIGAID)
)

INSERT INTO KNJIGA
VALUES('23F5G66','HSD7834','ROMEO I JULIJA'),
('VG356G7','NJ87HG6','ZOVEM SE CRVENO'),
('VDFS345','BH67GT5','SEOBE'),
('BH4352D','HGIK987','NOCNA SKOLA');
GO

INSERT INTO CITALAC
VALUES(25060047,'NEVENA','DJORDJEVIC','VRBOVAC','MILOSA OBILICA','0645778902'),
(23675890,'MILOS','SIMIC','SMEDEREVO','KRALJA PETRA','0654738229'),
(453627189,'NIKOLINA','STOJANOVIC','MIHAJLOVAC','VUKA KARADZICA','0607886533'),
(322123456,'PETRA','PETROVIC','SMEDEREVO','OSLOBODJENJA 12','0645332178');
GO

INSERT INTO NA_CITANJU
VALUES(1,2,'2022-03-12','2022-03-22'),
(2,4,'2021-12-14','2022-02-12'),
(4,1,'2022-01-14','2022-02-03'),
(3,3,'2022-03-24',NULL);
GO

INSERT INTO IZDAVAC
VALUES('LAGUNA','VUKA KARADZICA'),
('DELFI','BANJICKA 15'),
('LAGUNA','JADRANSKA ULICA'),
('VULKAN','KESTENOVA ULICA');
GO

INSERT INTO AUTOR
VALUES('JOVAN','KISIC','1980-12-12','BEOGRADSKA','DOKTOR'),
('DESANKA','MAKSIMOVIC','1954-06-24','CVETNA ULICA','MAGISTAR'),
('ORHAN','PAMUK','1965-07-18','SEDMOG JULA','DOKTOR'),
('FILIP','MAKSIMOVIC','1976-03-23','IZVORSKA','MAGISTAR');
GO

INSERT INTO NAPISALI
VALUES(1,3),
(2,4),
(4,1),
(3,2);
GO

INSERT INTO IZDALI
VALUES(2,3,'2000'),
(1,4,'1999'),
(3,1,'2001'),
(4,2,'1998');
GO

SELECT I.IZDAVACID, NAZIVIZDAVACA FROM IZDAVAC I INNER JOIN IZDALI II ON I.IZDAVACID = II.IZDAVACID 
INNER JOIN KNJIGA K ON K.KNJIGAID = II.KNJIGAID WHERE NAZIV = 'SEOBE'


/*prikazi podatke po izdavacima(izdavacid i naziv izdavaca) za sve izdavace koji su izdali knjigu sa odgovarajucim
naslovom(zadaje se kao parametar)*/
CREATE PROCEDURE PO_IZDAVACIMA
(@NAZIV CHAR(20))
AS
BEGIN
SELECT I.IZDAVACID, NAZIVIZDAVACA FROM IZDAVAC I LEFT JOIN IZDALI II ON I.IZDAVACID = II.IZDAVACID 
LEFT JOIN KNJIGA K ON K.KNJIGAID = II.KNJIGAID WHERE NAZIV = @NAZIV
END

EXECUTE PO_IZDAVACIMA 'ROMEO I JULIJA'


/*prikazati podatke o citaocima(ime, prezime, telefon) za one citaoce koji su 
procitali sva dela pisca cije su ime i prezime paremetri*/


/*prikazati ime i prezime autora, godinu iznajmljivanja knjige, broj iznajmljivanja knjiga tog autora u godini
za poslednjih @g godina i za autore cije su knjige izdavane najmanje @p puta*/
CREATE PROCEDURE prvi @g INT, @p INT
AS
BEGIN
SELECT ime, prezime, 
    (SELECT COUNT(*) 
    FROM NA_CITANJU n 
    LEFT JOIN KNJIGA k ON n.KNJIGAID = k.KNJIGAID 
    LEFT JOIN NAPISALI nn ON nn.KNJIGAID = k.KNJIGAID 
    WHERE DATEPART(year,n.DATUMUZIMANJA) >= @g AND nn.AUTORID = a.AUTORID) 
FROM AUTOR a 
WHERE 
    (SELECT COUNT(*) 
    FROM NA_CITANJU n 
    LEFT JOIN KNJIGA k ON n.KNJIGAID = k.KNJIGAID 
    LEFT JOIN NAPISALI nn ON nn.KNJIGAID = k.KNJIGAID 
    WHERE nn.AUTORID = a.AUTORID) >= @p;
END
EXECUTE prvi 2022, 5



CREATE PROCEDURE treci @p INT
AS
BEGIN
SELECT c.citalacid, ime, prezime, COUNT(*) 
FROM NA_CITANJU n 
LEFT JOIN CITALAC c ON c.CITALACID = n.CITALACID
WHERE n.DATUMVRACANJA IS NULL
GROUP BY c.citalacid, ime, prezime 
HAVING COUNT(*) > @p 
ORDER BY COUNT(*)
END
EXECUTE treci 0



CREATE PROCEDURE cetvrti @ime CHAR(30), @prezime CHAR(30)
AS
BEGIN
SELECT * FROM CITALAC c
WHERE 
    (SELECT COUNT(*) 
    FROM NA_CITANJU n 
    WHERE n.CITALACID = c.CITALACID) 
    = 
    (SELECT COUNT(*) 
    FROM KNJIGA) AND c.IME = @ime AND c.PREZIME = @prezime
END
EXECUTE cetvrti 'FILIP', 'MAKSIMOVIC'